name: CI

on:
  push:
    branches: [main, master]
    paths-ignore:
      - "**.md"
      - ".gitignore"
      - "LICENSE"
  pull_request:
    branches: [main, master]
    paths-ignore:
      - "**.md"
      - ".gitignore"
      - "LICENSE"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: make test
